name: linters

on:
  pull_request:

jobs:
  lint-server:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environment Information
        run: npx envinfo
      - name: Lint server
        run: |
          cd src/server
          npm ci
          npm run lint --if-present
  lint-view:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environment Information
        run: npx envinfo
      - name: Lint view
        run: |
          cd src/view
          npm ci
          npm run lint --if-present
